# This is a basic workflow to help you get started with Actions

name: Update i18n

# Controls when the action will run. 
on: 

  push:
    branches: 
      - i18n-updates-1
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: i18n-updates-1

      # Runs a set of commands using the runners shell
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: update submodules
        run: git add -v . && git commit -m "bumping submodules"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: i18n-updates-1
